---
title: "Lab Set 4"
author: "My Name"
output:
  pdf_document:
    fig_caption: yes
    number_sections: true
header-includes:
  - |
    ```{=latex}
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
      breaksymbolleft={}, 
      showspaces = false,
      showtabs = false,
      breaklines,
      commandchars=\\\{\}
    }
    ```
---


```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  tidy.opts=list(width.cutoff=70),
  tidy=TRUE
)
```

# Lab 10

## Task 1

Which linkage method gives the strongest clustering structure?

> Your response

## Task 2

Looking at both the biplot and the variable contributions, first describe the clustering patterns, then posit an explanation for them. 

> Your response

# Lab 11

## Task 1

Why might it be important to periodize data from "the ground up" (using a technique like VNC), rather than just splitting data into intervals of, say, 10, 25, or 50 years?

> Your response

Following the conventions described in Brezina (pgs. 240-241) report the results produced by the "witch hunt" VNC.

> Your response

# Lab 12

## Task 1

Our model predicts all but 55 were written by Madison. Our model is not particularly confident about that result. This hews pretty closely to Mosteller & Wallace's findings, through they come down (sort of) on the side of Madison for 55. However, they also acknowledge that the evidence is weak and not very convincing.

Give at least 3 possible factors that might explain that low probability?


