{
  "hash": "1a976a15002502c7cae6ef3159e5f854",
  "result": {
    "engine": "knitr",
    "markdown": "\n# Distributions\n\n## Prepare a corpus\n\n### Load the needed packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gt)\nlibrary(quanteda)\nlibrary(quanteda.textstats)\nlibrary(tidyverse)\n```\n:::\n\n\n\n### Load a corpus\n\nThe  repository comes with some data sets. The conventional way to format text data prior to processing is as a table with a column of document ids (which correspond to the the file names) and a column of texts. Such a table is easy to create from text data on your own local drive using the package [**readtext**](https://readtext.quanteda.io/articles/readtext_vignette.html).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(\"../data/sample_corpus.rda\")\nload(\"../data/multiword_expressions.rda\")\n```\n:::\n\n\n\nTo peek at the data, we'll look at the first 100 characters in the \"text\" column of the first row:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nsample_corpus |>\n  mutate(text = substr(text, start = 1, stop = 100)) |>\n  head(10) |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wmtlishyxi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wmtlishyxi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wmtlishyxi thead, #wmtlishyxi tbody, #wmtlishyxi tfoot, #wmtlishyxi tr, #wmtlishyxi td, #wmtlishyxi th {\n  border-style: none;\n}\n\n#wmtlishyxi p {\n  margin: 0;\n  padding: 0;\n}\n\n#wmtlishyxi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wmtlishyxi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wmtlishyxi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wmtlishyxi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wmtlishyxi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wmtlishyxi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wmtlishyxi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wmtlishyxi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wmtlishyxi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wmtlishyxi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wmtlishyxi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wmtlishyxi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wmtlishyxi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wmtlishyxi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wmtlishyxi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wmtlishyxi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wmtlishyxi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wmtlishyxi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wmtlishyxi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wmtlishyxi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wmtlishyxi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wmtlishyxi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wmtlishyxi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wmtlishyxi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wmtlishyxi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wmtlishyxi .gt_left {\n  text-align: left;\n}\n\n#wmtlishyxi .gt_center {\n  text-align: center;\n}\n\n#wmtlishyxi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wmtlishyxi .gt_font_normal {\n  font-weight: normal;\n}\n\n#wmtlishyxi .gt_font_bold {\n  font-weight: bold;\n}\n\n#wmtlishyxi .gt_font_italic {\n  font-style: italic;\n}\n\n#wmtlishyxi .gt_super {\n  font-size: 65%;\n}\n\n#wmtlishyxi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wmtlishyxi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wmtlishyxi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wmtlishyxi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wmtlishyxi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wmtlishyxi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wmtlishyxi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wmtlishyxi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wmtlishyxi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"doc_id\">doc_id</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"text\">text</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_01</td>\n<td headers=\"text\" class=\"gt_row gt_left\">Teachers and other school personnel are often counseled to use research findings in making curricula</td></tr>\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_02</td>\n<td headers=\"text\" class=\"gt_row gt_left\">Abstract Does the conflict in El Salvador, conceptualized by the U.S. government as a battle in the </td></tr>\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_03</td>\n<td headers=\"text\" class=\"gt_row gt_left\">January 17, 1993, will mark the 100th anniversary of the deposing of the Hawaiian monarchy. \"Prior t</td></tr>\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_04</td>\n<td headers=\"text\" class=\"gt_row gt_left\">Thirty years have passed since the T1961 meeting of the National Council for the Social Studies in C</td></tr>\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_05</td>\n<td headers=\"text\" class=\"gt_row gt_left\">ABSTRACT -- A common property resource with open access, such as a fishery, will be used to excess w</td></tr>\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_06</td>\n<td headers=\"text\" class=\"gt_row gt_left\">Despite some encouraging signs and hopeful expectations that democracy has made reasonable progress </td></tr>\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_07</td>\n<td headers=\"text\" class=\"gt_row gt_left\">evaluation component. Similarly, Stewart ( 1982,1989 ) has shown that a common response to unfamilia</td></tr>\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_08</td>\n<td headers=\"text\" class=\"gt_row gt_left\">Section: Education \"A lab is where you do science\" ( Thornton 1972 ). An investigative laboratory ( </td></tr>\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_09</td>\n<td headers=\"text\" class=\"gt_row gt_left\">In 1968, the thirtieth anniversary issue of the Journal of Politics celebrated the great advance in </td></tr>\n    <tr><td headers=\"doc_id\" class=\"gt_row gt_left\">acad_10</td>\n<td headers=\"text\" class=\"gt_row gt_left\">monologue -- and of Novas Calvo's story -- may thus be clarified, not as that of facilitating an obj</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n### Load functions\n\nThe repository also contains a number of useful functions. Here, will load some that will calculate a number of common dispersion measures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsource(\"../R/dispersion_functions.R\")\n```\n:::\n\n\n### Create and corpus\n\nMake a corpus object.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsc <- corpus(sample_corpus)\n```\n:::\n\n\nAnd check the result:\n\n\n::: {#tbl-summary .cell tbl-cap='Partial summary of sample corpus.'}\n\n```{.r .cell-code  code-fold=\"true\"}\nsc |>\n  summary() |>\n  head(10) |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"iauucbkwob\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iauucbkwob table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iauucbkwob thead, #iauucbkwob tbody, #iauucbkwob tfoot, #iauucbkwob tr, #iauucbkwob td, #iauucbkwob th {\n  border-style: none;\n}\n\n#iauucbkwob p {\n  margin: 0;\n  padding: 0;\n}\n\n#iauucbkwob .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iauucbkwob .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iauucbkwob .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iauucbkwob .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iauucbkwob .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iauucbkwob .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iauucbkwob .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iauucbkwob .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iauucbkwob .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iauucbkwob .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iauucbkwob .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iauucbkwob .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iauucbkwob .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iauucbkwob .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iauucbkwob .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iauucbkwob .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iauucbkwob .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iauucbkwob .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iauucbkwob .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iauucbkwob .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iauucbkwob .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iauucbkwob .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iauucbkwob .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iauucbkwob .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iauucbkwob .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iauucbkwob .gt_left {\n  text-align: left;\n}\n\n#iauucbkwob .gt_center {\n  text-align: center;\n}\n\n#iauucbkwob .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iauucbkwob .gt_font_normal {\n  font-weight: normal;\n}\n\n#iauucbkwob .gt_font_bold {\n  font-weight: bold;\n}\n\n#iauucbkwob .gt_font_italic {\n  font-style: italic;\n}\n\n#iauucbkwob .gt_super {\n  font-size: 65%;\n}\n\n#iauucbkwob .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iauucbkwob .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iauucbkwob .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iauucbkwob .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iauucbkwob .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iauucbkwob .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iauucbkwob .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#iauucbkwob .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#iauucbkwob div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Text\">Text</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Types\">Types</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Tokens\">Tokens</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sentences\">Sentences</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_01</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">842</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2818</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">95</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_02</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">983</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2845</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">88</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_03</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">968</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2885</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">126</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_04</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">1017</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2864</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">102</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_05</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">914</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2837</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">109</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_06</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">1007</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2813</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">86</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_07</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">663</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2952</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">92</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_08</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">870</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2830</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">118</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_09</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">980</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2899</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">131</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_10</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">1118</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2883</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">77</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Document variables (Name your files systematically!)\n\n::: callout-important\nFile names can encode important meta-data. In this case, the names include text-types, much like the [Corpus of Contemporary American English](https://www.english-corpora.org/coca/help/texts.asp).\n\nThis is **extremely important**. When you build your own corpora, you want to purposefully and systematically name your files and organize your directories. This will save you time and effort later in your analysis.\n:::\n\nWe are now going to extract the meta-data from the file names and pass them as a variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndoc_categories <- str_extract(sample_corpus$doc_id, \"^[a-z]+\")\n```\n:::\n\n\nCheck the result:\n\n\n::: {.cell tbl-cap='Document categories.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"atfwrgywax\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#atfwrgywax table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#atfwrgywax thead, #atfwrgywax tbody, #atfwrgywax tfoot, #atfwrgywax tr, #atfwrgywax td, #atfwrgywax th {\n  border-style: none;\n}\n\n#atfwrgywax p {\n  margin: 0;\n  padding: 0;\n}\n\n#atfwrgywax .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: 50%;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#atfwrgywax .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#atfwrgywax .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#atfwrgywax .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#atfwrgywax .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#atfwrgywax .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#atfwrgywax .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#atfwrgywax .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#atfwrgywax .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#atfwrgywax .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#atfwrgywax .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#atfwrgywax .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#atfwrgywax .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#atfwrgywax .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#atfwrgywax .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atfwrgywax .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#atfwrgywax .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#atfwrgywax .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#atfwrgywax .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atfwrgywax .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#atfwrgywax .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atfwrgywax .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#atfwrgywax .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atfwrgywax .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#atfwrgywax .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#atfwrgywax .gt_left {\n  text-align: left;\n}\n\n#atfwrgywax .gt_center {\n  text-align: center;\n}\n\n#atfwrgywax .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#atfwrgywax .gt_font_normal {\n  font-weight: normal;\n}\n\n#atfwrgywax .gt_font_bold {\n  font-weight: bold;\n}\n\n#atfwrgywax .gt_font_italic {\n  font-style: italic;\n}\n\n#atfwrgywax .gt_super {\n  font-size: 65%;\n}\n\n#atfwrgywax .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#atfwrgywax .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#atfwrgywax .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#atfwrgywax .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#atfwrgywax .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#atfwrgywax .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#atfwrgywax .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#atfwrgywax .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#atfwrgywax div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"doc_cats\">doc_cats</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"doc_cats\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"doc_cats\" class=\"gt_row gt_left\">blog</td></tr>\n    <tr><td headers=\"doc_cats\" class=\"gt_row gt_left\">fic</td></tr>\n    <tr><td headers=\"doc_cats\" class=\"gt_row gt_left\">mag</td></tr>\n    <tr><td headers=\"doc_cats\" class=\"gt_row gt_left\">news</td></tr>\n    <tr><td headers=\"doc_cats\" class=\"gt_row gt_left\">spok</td></tr>\n    <tr><td headers=\"doc_cats\" class=\"gt_row gt_left\">tvm</td></tr>\n    <tr><td headers=\"doc_cats\" class=\"gt_row gt_left\">web</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nWe will now assign the variable to the corpus. The following command might look backwards, with the function on the left hand side of the **<-** operator. That is because it's an accessor function, which lets us add or modify data in an object. You can tell when a function is an accessor function like this because its help file will show that you can use it with **<-**, for example in **?docvars**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndocvars(sc, field = \"text_type\") <- doc_categories\n```\n:::\n\n\nAnd check the summary again:\n\n\n::: {.cell tbl-cap='Partial summary of sample corpus.'}\n\n```{.r .cell-code  code-fold=\"true\"}\nsc |>\n  summary() |>\n  head(10) |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yvpvsctcff\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yvpvsctcff table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yvpvsctcff thead, #yvpvsctcff tbody, #yvpvsctcff tfoot, #yvpvsctcff tr, #yvpvsctcff td, #yvpvsctcff th {\n  border-style: none;\n}\n\n#yvpvsctcff p {\n  margin: 0;\n  padding: 0;\n}\n\n#yvpvsctcff .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yvpvsctcff .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yvpvsctcff .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yvpvsctcff .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yvpvsctcff .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yvpvsctcff .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yvpvsctcff .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yvpvsctcff .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yvpvsctcff .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yvpvsctcff .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yvpvsctcff .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yvpvsctcff .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yvpvsctcff .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yvpvsctcff .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yvpvsctcff .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvpvsctcff .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yvpvsctcff .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yvpvsctcff .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yvpvsctcff .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvpvsctcff .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yvpvsctcff .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvpvsctcff .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yvpvsctcff .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvpvsctcff .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yvpvsctcff .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yvpvsctcff .gt_left {\n  text-align: left;\n}\n\n#yvpvsctcff .gt_center {\n  text-align: center;\n}\n\n#yvpvsctcff .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yvpvsctcff .gt_font_normal {\n  font-weight: normal;\n}\n\n#yvpvsctcff .gt_font_bold {\n  font-weight: bold;\n}\n\n#yvpvsctcff .gt_font_italic {\n  font-style: italic;\n}\n\n#yvpvsctcff .gt_super {\n  font-size: 65%;\n}\n\n#yvpvsctcff .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yvpvsctcff .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yvpvsctcff .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yvpvsctcff .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yvpvsctcff .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yvpvsctcff .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yvpvsctcff .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yvpvsctcff .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yvpvsctcff div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Text\">Text</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Types\">Types</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Tokens\">Tokens</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Sentences\">Sentences</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"text_type\">text_type</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_01</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">842</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2818</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">95</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_02</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">983</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2845</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">88</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_03</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">968</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2885</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">126</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_04</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">1017</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2864</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">102</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_05</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">914</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2837</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">109</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_06</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">1007</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2813</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">86</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_07</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">663</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2952</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">92</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_08</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">870</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2830</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">118</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_09</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">980</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2899</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">131</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n    <tr><td headers=\"Text\" class=\"gt_row gt_left\">acad_10</td>\n<td headers=\"Types\" class=\"gt_row gt_right\">1118</td>\n<td headers=\"Tokens\" class=\"gt_row gt_right\">2883</td>\n<td headers=\"Sentences\" class=\"gt_row gt_right\">77</td>\n<td headers=\"text_type\" class=\"gt_row gt_left\">acad</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n::: callout-warning\nAssigning **docvars** is based entirely on ordering. In other words, you are simply attaching a vector of categories to the corpus object. There is no merging by shared keys. Thus, you always need to be sure that your **docvars** are in the same order as your **doc_ids**. This is the reason why we extracted them directly from the **doc_ids**.\n:::\n\n## Tokenize the corpus\n\nWe'll use **quanteda** to tokenize. And after tokenization, we'll convert them to lower case. *Why do that here?* As a next step, we'll being combining tokens like *a* and *lot* into single units. And we'll be using a list of expressions that isn't case sensitive.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsc_tokens <- tokens(sc, include_docvars=TRUE, remove_punct = TRUE, remove_numbers = TRUE, remove_symbols = TRUE, what = \"word\")\n\nsc_tokens <- tokens_tolower(sc_tokens)\n```\n:::\n\n\n## Multi-word Expressions\n\nAn issue that we run into frequently with corpus analysis is what to do with multi-word expressions. For example, consider a common English quantifier: \"a lot\". Typical tokenization rules will split this into two tokens: *a* and *lot*. But counting *a lot* as a single unit might be important depending on our task. We have a way of telling **quanteda** to account for these tokens.\n\nAll that we need is a list of multi-word expressions.\n\nThe **cmu.textstat** comes with an example of an mwe list called **multiword_expressions**:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Examples of multi-word expressions.\n\n|                  |\n|:-----------------|\n|winter haven      |\n|with a view to    |\n|with reference to |\n|with regard to    |\n|with relation to  |\n|with respect to   |\n\n\n:::\n:::\n\n\nThe **tokens_compound()** function looks for token sequences that match our list\nand combines them using an underscore.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsc_tokens <- tokens_compound(sc_tokens, pattern = phrase(multiword_expressions))\n```\n:::\n\n\n## Create a document-feature matrix\n\nWith our tokens object we can now create a document-feature-matrix using the\n**dfm()** function. As a reminder, a **dfm** is table with one row per document in the corpus, and one column per unique token in the corpus. Each cell contains a count of how many times a token shows up in that document.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsc_dfm <- dfm(sc_tokens)\n```\n:::\n\n\nNext we'll create a **dfm** with proportionally weighted counts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop_dfm <- dfm_weight(sc_dfm, scheme = \"prop\")\n```\n:::\n\n\n## Token distributions\n\n### Distributions of *the*\n\nLet's start by selecting frequencies of the most common token in the corpus:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfreq_df <- textstat_frequency(sc_dfm) %>%\n  data.frame(stringsAsFactors = F)\n```\n:::\n\n::: {.cell tbl-cap='The 10 most frequent tokens in the sample corpus.'}\n\n```{.r .cell-code  code-fold=\"true\"}\nfreq_df |>\n  head(10) |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tjrxddrgav\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tjrxddrgav table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tjrxddrgav thead, #tjrxddrgav tbody, #tjrxddrgav tfoot, #tjrxddrgav tr, #tjrxddrgav td, #tjrxddrgav th {\n  border-style: none;\n}\n\n#tjrxddrgav p {\n  margin: 0;\n  padding: 0;\n}\n\n#tjrxddrgav .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tjrxddrgav .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tjrxddrgav .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tjrxddrgav .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tjrxddrgav .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tjrxddrgav .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tjrxddrgav .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tjrxddrgav .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tjrxddrgav .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tjrxddrgav .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tjrxddrgav .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tjrxddrgav .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tjrxddrgav .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tjrxddrgav .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tjrxddrgav .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tjrxddrgav .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tjrxddrgav .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tjrxddrgav .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tjrxddrgav .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tjrxddrgav .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tjrxddrgav .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tjrxddrgav .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tjrxddrgav .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tjrxddrgav .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tjrxddrgav .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tjrxddrgav .gt_left {\n  text-align: left;\n}\n\n#tjrxddrgav .gt_center {\n  text-align: center;\n}\n\n#tjrxddrgav .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tjrxddrgav .gt_font_normal {\n  font-weight: normal;\n}\n\n#tjrxddrgav .gt_font_bold {\n  font-weight: bold;\n}\n\n#tjrxddrgav .gt_font_italic {\n  font-style: italic;\n}\n\n#tjrxddrgav .gt_super {\n  font-size: 65%;\n}\n\n#tjrxddrgav .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tjrxddrgav .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tjrxddrgav .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tjrxddrgav .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tjrxddrgav .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tjrxddrgav .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tjrxddrgav .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tjrxddrgav .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tjrxddrgav div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"feature\">feature</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"frequency\">frequency</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"rank\">rank</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"docfreq\">docfreq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"group\">group</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">the</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">50920</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">1</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">399</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">and</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">25232</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">2</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">398</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">to</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">24753</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">3</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">397</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">of</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">22060</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">4</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">399</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">a</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">21614</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">5</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">398</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">in</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">15969</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">6</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">399</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">i</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">12568</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">7</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">348</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">that</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">12537</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">8</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">396</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">you</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">10951</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">9</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">341</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n    <tr><td headers=\"feature\" class=\"gt_row gt_left\">is</td>\n<td headers=\"frequency\" class=\"gt_row gt_right\">9901</td>\n<td headers=\"rank\" class=\"gt_row gt_right\">10</td>\n<td headers=\"docfreq\" class=\"gt_row gt_right\">389</td>\n<td headers=\"group\" class=\"gt_row gt_left\">all</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nFrom the weighted **dfm**, we can select any token that we'd like to look at more closely. In this case, we'll select the most frequent token: *the*.\n\nAfter selecting the variable, we will convert the data into a more friendly data structure.\n\nThere are easier ways of doing this, but the first bit of the code-chunk allows us to filter by rank and return a character vector that we can pass. This way, we can find a word of any arbitrary rank.\n\nAlso note how the **rename()** function is set up. Let's say our token is *the*. The **dfm_select()** function would result with a column named **the** that we'd want to rename **RF**. So our typical syntax would be: **rename(RF = the)**. In the chunk below, however, our column name is the variable **word**. To pass that variable to **rename**, we use **!!name(word)**.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nword <- freq_df %>% \n  filter(rank == 1) %>% \n  dplyr::select(feature) %>%\n  as.character()\n\nword_df <- dfm_select(prop_dfm, word, valuetype = \"fixed\") # select the token\n\nword_df <- word_df %>% \n  convert(to = \"data.frame\") %>% \n  cbind(docvars(word_df)) %>% \n  rename(RF = !!as.name(word)) %>% \n  mutate(RF = RF*1000000)\n```\n:::\n\n\nWith that data it is a simple matter to generate basic summary statistics using the **group_by()** function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_table <- word_df %>% \n  group_by(text_type) %>%\n  summarize(MEAN = mean(RF),\n              SD = sd(RF),\n              N = n())\n```\n:::\n\n::: {.cell tbl-cap='Means and standard deviations by text-type.'}\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary_table |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ehkdqhokjf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ehkdqhokjf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ehkdqhokjf thead, #ehkdqhokjf tbody, #ehkdqhokjf tfoot, #ehkdqhokjf tr, #ehkdqhokjf td, #ehkdqhokjf th {\n  border-style: none;\n}\n\n#ehkdqhokjf p {\n  margin: 0;\n  padding: 0;\n}\n\n#ehkdqhokjf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ehkdqhokjf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ehkdqhokjf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ehkdqhokjf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ehkdqhokjf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ehkdqhokjf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ehkdqhokjf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ehkdqhokjf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ehkdqhokjf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ehkdqhokjf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ehkdqhokjf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ehkdqhokjf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ehkdqhokjf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ehkdqhokjf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ehkdqhokjf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehkdqhokjf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ehkdqhokjf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ehkdqhokjf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ehkdqhokjf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehkdqhokjf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ehkdqhokjf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehkdqhokjf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ehkdqhokjf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehkdqhokjf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ehkdqhokjf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ehkdqhokjf .gt_left {\n  text-align: left;\n}\n\n#ehkdqhokjf .gt_center {\n  text-align: center;\n}\n\n#ehkdqhokjf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ehkdqhokjf .gt_font_normal {\n  font-weight: normal;\n}\n\n#ehkdqhokjf .gt_font_bold {\n  font-weight: bold;\n}\n\n#ehkdqhokjf .gt_font_italic {\n  font-style: italic;\n}\n\n#ehkdqhokjf .gt_super {\n  font-size: 65%;\n}\n\n#ehkdqhokjf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ehkdqhokjf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ehkdqhokjf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ehkdqhokjf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ehkdqhokjf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ehkdqhokjf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ehkdqhokjf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ehkdqhokjf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ehkdqhokjf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"text_type\">text_type</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"MEAN\">MEAN</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SD\">SD</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"N\">N</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"text_type\" class=\"gt_row gt_left\">acad</td>\n<td headers=\"MEAN\" class=\"gt_row gt_right\">68619.64</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">18327.10</td>\n<td headers=\"N\" class=\"gt_row gt_right\">50</td></tr>\n    <tr><td headers=\"text_type\" class=\"gt_row gt_left\">blog</td>\n<td headers=\"MEAN\" class=\"gt_row gt_right\">51270.54</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">13389.38</td>\n<td headers=\"N\" class=\"gt_row gt_right\">50</td></tr>\n    <tr><td headers=\"text_type\" class=\"gt_row gt_left\">fic</td>\n<td headers=\"MEAN\" class=\"gt_row gt_right\">54202.41</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">14254.79</td>\n<td headers=\"N\" class=\"gt_row gt_right\">50</td></tr>\n    <tr><td headers=\"text_type\" class=\"gt_row gt_left\">mag</td>\n<td headers=\"MEAN\" class=\"gt_row gt_right\">57117.76</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">13986.30</td>\n<td headers=\"N\" class=\"gt_row gt_right\">50</td></tr>\n    <tr><td headers=\"text_type\" class=\"gt_row gt_left\">news</td>\n<td headers=\"MEAN\" class=\"gt_row gt_right\">50574.84</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">18333.09</td>\n<td headers=\"N\" class=\"gt_row gt_right\">50</td></tr>\n    <tr><td headers=\"text_type\" class=\"gt_row gt_left\">spok</td>\n<td headers=\"MEAN\" class=\"gt_row gt_right\">42693.44</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">9727.79</td>\n<td headers=\"N\" class=\"gt_row gt_right\">50</td></tr>\n    <tr><td headers=\"text_type\" class=\"gt_row gt_left\">tvm</td>\n<td headers=\"MEAN\" class=\"gt_row gt_right\">32532.85</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">11981.88</td>\n<td headers=\"N\" class=\"gt_row gt_right\">50</td></tr>\n    <tr><td headers=\"text_type\" class=\"gt_row gt_left\">web</td>\n<td headers=\"MEAN\" class=\"gt_row gt_right\">60592.68</td>\n<td headers=\"SD\" class=\"gt_row gt_right\">21641.35</td>\n<td headers=\"N\" class=\"gt_row gt_right\">50</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nAnd we can inspect a histogram of the frequencies. To set the width of our bins we'll use the Freedman-Diaconis rule. The bin-width is set to:\n$$h = 2 x \\frac{IQR(x)}{n^{1/3}}$$\n\nSo the number of bins is (max-min)/h, where n is the number of observations, max is the maximum value and min is the minimum value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbin_width <- function(x){\n  2 * IQR(x) / length(x)^(1/3)\n  }\n```\n:::\n\n\nNow we can plot a histogram. We're also adding a dashed line showing the mean. Note we're also going to use the **scales** package to remove scientific notation from our tick labels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(word_df,aes(RF)) + \n  geom_histogram(binwidth = bin_width(word_df$RF), colour=\"black\", fill=\"white\", linewidth=.25) +\n  geom_vline(aes(xintercept=mean(RF)), color=\"red\", linetype=\"dashed\", linewidth=.5) +\n  theme_classic() +\n  scale_x_continuous(labels = scales::comma) +\n  xlab(\"RF (per mil. words)\")\n```\n\n::: {.cell-output-display}\n![Histogram of the token *the*](distributions_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n### Distributions of *the* and *of*\n\nNow let's try plotting histograms of two tokens on the same plot. First we're going to use regular expressions to select the columns. The carat or hat **^** looks for the start of line. Without it, we would also get words like \"blather\". The dollar symbol **$** looks for the end of a line. The straight line | means OR. Think about how useful this flexibility can be. You could, for example, extract all words that end in *-ion*.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note \"regex\" rather than \"fixed\"\nword_df <- dfm_select(prop_dfm, \"^the$|^of$\", valuetype = \"regex\")\n\n# Now we'll convert our selection and normalize to 10000 words.\nword_df <- word_df %>% \n  convert(to = \"data.frame\") %>%\n  mutate(the = the*10000) %>%\n  mutate(of = of*10000)\n\n# Use \"pivot_longer\" to go from a wide format to a long one\nword_df <- word_df %>% \n  pivot_longer(!doc_id, names_to = \"token\", values_to = \"RF\") %>% \n  mutate(token = factor(token))\n```\n:::\n\n\nNow let's make a new histogram. Here we assign the values of color and fill to the \"token\" column. We also make the columns a little transparent using the \"alpha\" setting.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(word_df,aes(x = RF, color = token, fill = token)) + \n  geom_histogram(binwidth = bin_width(word_df$RF), alpha=.5, position = \"identity\") +\n  theme_classic() +\n  xlab(\"RF (per mil. words)\") +\n  theme(axis.text = element_text(size=5))\n```\n\n::: {.cell-output-display}\n![Histogram of the tokens *the* and *of*.](distributions_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nIf we don't want overlapping histograms, we can use **facet_wrap()** to split the plots.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(word_df,aes(x = RF, color = token, fill = token)) + \n  geom_histogram(binwidth = bin_width(word_df$RF), alpha=.5, position = \"identity\") +\n  theme_classic() +\n  theme(axis.text = element_text(size=5)) +\n  theme(legend.position = \"none\") +\n  xlab(\"RF (per mil. words)\") +\n  facet_wrap(~ token)\n```\n\n::: {.cell-output-display}\n![Histogram of the tokens *the* and *of*.](distributions_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n::: callout-important\n## Pause for Lab Set Question\n\nComplete [Task 1 in Lab Set 2](../lab_sets/LabSet_02.qmd#distributions).\n:::\n\n## Dispersion\n\nWe can also calculate dispersion, and there are a variety of measures at our disposal. Our toolkit has several functions for producing these calculations.\n\nFor example, we can find the dispersion of any specific token:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nthe <- dispersions_token(sc_dfm, \"the\") %>% unlist()\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Dispersion measures for the token \\textit{the}.\n\n                                                                                      \n--------------------------------------------------------------------------  ----------\nAbsolute frequency                                                           50920.000\nPer_10.5                                                                      5240.015\nRelative entropy of all sizes of the corpus parts                                1.000\nRange                                                                          399.000\nMaxmin                                                                         292.000\nStandard deviation                                                              45.926\nVariation coefficient                                                            0.361\nChi-square                                                                    6295.422\nJuilland et al.'s D (based on equally-sized corpus parts)                        0.982\nJuilland et al.'s D (not requiring equally-sized corpus parts)                   0.982\nCarroll's D2                                                                     0.989\nRosengren's S (based on equally-sized corpus parts)                              0.963\nRosengren's S (not requiring equally-sized corpus parts)                         0.966\nLyne's D3 (not requiring equally-sized corpus parts)                             0.968\nDistributional consistency DC                                                    0.963\nInverse document frequency IDF                                                   0.004\nEngvall's measure                                                            50792.700\nJuilland et al.'s U (based on equally-sized corpus parts)                    50000.333\nJuilland et al.'s U (not requiring equally-sized corpus parts)               50010.750\nCarroll's Um (based on equally sized corpus parts)                           50342.268\nRosengren's Adjusted Frequency (based on equally sized corpus parts)         49032.932\nRosengren's Adjusted Frequency (not requiring equally sized corpus parts)    49185.689\nKromer's Ur                                                                   2135.564\nDeviation of proportions DP                                                      0.139\nDeviation of proportions DP (normalized)                                         0.139\n--------------------------------------------------------------------------  ----------\n\n\n:::\n:::\n\n\nAnd let's try another token to compare:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- dispersions_token(sc_dfm, \"data\") %>% unlist()\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Deviation of Proportions for the tokens \\textit{the} and \\textit{data}.\n\n                                 the    data\n----------------------------  ------  ------\nDeviation of proportions DP    0.139   0.846\n\n\n:::\n:::\n\n\n::: callout-important\n## Pause for Lab Set Question\n\nComplete [Task 2 in Lab Set 2](../lab_sets/LabSet_02.qmd#distributions).\n:::\n\n### Dispersions for all tokens\n\nWe can also calculate selected dispersion measures for all tokens using **dispersions_all()**:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- dispersions_all(sc_dfm)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Dispersion measures for all tokens.\n\nToken       AF   Per_10.5   Carrolls_D2   Rosengrens_S   Lynes_D3      DC   Juillands_D      DP   DP_norm\n------  ------  ---------  ------------  -------------  ---------  ------  ------------  ------  --------\nthe      50920   5240.015         0.989          0.966      0.968   0.963         0.982   0.139     0.139\nand      25232   2596.545         0.990          0.970      0.973   0.967         0.983   0.123     0.124\nto       24753   2547.252         0.993          0.980      0.983   0.976         0.987   0.090     0.090\nof       22060   2270.124         0.978          0.933      0.935   0.932         0.974   0.199     0.199\na        21614   2224.228         0.992          0.977      0.978   0.973         0.986   0.109     0.109\nin       15969   1643.319         0.988          0.962      0.963   0.960         0.981   0.146     0.146\n\n\n:::\n:::\n\n\n## Generating a frequency table\n\nAlternatively, **frequency_table()** returns only Deviation of Proportions and Average Reduced Frequency.\n\nNote that ARF requires a tokens object and takes a couple of minutes to calculate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nft <- frequency_table(sc_tokens)\n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\n\nTable: Frequency and dispersion measures for all tokens.\n\n     Token       AF   Per_10.5         ARF      DP\n---  ------  ------  ---------  ----------  ------\n1    the      50920   5240.015   31901.106   0.139\n2    and      25232   2596.545   15914.149   0.123\n3    to       24753   2547.252   15468.494   0.090\n5    of       22060   2270.124   13089.728   0.199\n4    a        21614   2224.228   13239.704   0.109\n6    in       15969   1643.319    9772.267   0.146\n\n\n:::\n:::\n\n\n::: callout-important\n## Pause for Lab Set Question\n\nComplete [Task 3 in Lab Set 2](../lab_sets/LabSet_02.qmd#distributions).\n:::\n\n\n## Zipf's Law\n\nLet's plot rank against frequency for the 100 most frequent tokens in the sample corpus.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(freq_df %>% filter(rank < 101), aes(x = rank, y = frequency)) +\n  geom_point(shape = 1, alpha = .5) +\n  theme_classic() +\n  ylab(\"Absolute frequency\") +\n  xlab(\"Rank\")\n```\n\n::: {.cell-output-display}\n![Token rank vs. frequency.](distributions_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\nThe relationship you're seeing between the rank of a token and it's frequency holds true for almost any corpus and is referred to as **Zipf's Law** (see Brezina pg. 44).\n\n::: callout-important\n## Pause for Lab Set Question\n\nComplete [Task 4 in Lab Set 2](../lab_sets/LabSet_02.qmd#distributions).\n:::\n\n",
    "supporting": [
      "distributions_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}